### ISSUE TITLE
FIle Assets Manager

### ISSUE THREAD

**Issue by sandio** [WeAreAthlon/silla.io#29]
Manage assets using the persistent storage engine, not directlty scanning the file system.

**Comment by pnikolov** [comment]
I think [Responsive File Manager](http://www.responsivefilemanager.com) is a good reference in terms of functionality and look and feel.

**Comment by pnikolov** [comment]
There is a dedicated branch for this feature. It is still in progress: https://github.com/WeAreAthlon/silla.io/tree/feature/media-manager
