### ISSUE TITLE
Editable CMS Help page

### ISSUE THREAD

**Issue by sandio** [WeAreAthlon/silla.io#36]
Help CMS page should be editable from the CMS itself.

**Comment by pnikolov** [comment]
What would be the best approach in terms of text formatting?
- Regular `WYSIWYG` editor
- `Markdown`, `Textile`, etc. based editor?

**Comment by sandio** [comment]
`Markdown` seems popular these days. :suspect:

**Comment by pnikolov** [comment]
So can you recommend a `composer` managed `Markdown` parser that we can embed and user for this page? I think both options - `WYSIWYG` and `Markdown` should be available, @kmotsov and @kalins have experience with such feature.

**Comment by sandio** [comment]
This might be a good choice? http://parsedown.org/
A comparison between the most famous Markdown PHP parsers: http://parsedown.org/speed

**Comment by rozalia** [comment]
I propose to create a new table, which to be used for settings storage such as the help page. I have made a model of the table:
![screen shot 2015-06-26 at 4 39 59 pm](https://cloud.githubusercontent.com/assets/1941761/8378461/6aa91944-1c22-11e5-9bf5-449f5ff7b065.png)

**Comment by pnikolov** [comment]
:+1: We have already discussed that we need such a settings storage. The proposed table schema is nice. I would change the **key** and **name** columns to be **VARCHAR(255)**.
