### ISSUE TITLE
Filtering browser session cache isn't based per user

### ISSUE THREAD

**Issue by sandio** [WeAreAthlon/silla.io#37]
This affect the `DataTable` filtering, part of the CMS application.

**Comment by pnikolov** [comment]
@rozalia can you describe how to reproduce the bug?

**Comment by rozalia** [comment]
When two users logged in the `CMS` from one PC, the second user will have same `browser cache` as the first user i.e the filters that the first user has chosen will be saved

**Comment by pnikolov** [comment]
:+1:
