### ISSUE TITLE
Display Silla.IO's version somewhere in CMS

### ISSUE THREAD

**Issue by sandio** [WeAreAthlon/silla.io#39]
It will be helpful to know the framework+CMS version when using the CMS. I think it will be even cooler if when the version is clicked, it checks if there are new stable GitHub releases. An easier solution will be to link the version number on the CMS to the GitHub releases. What do you think @pnikolov ?

**Comment by pnikolov** [comment]
The proposed linking is the working solution. Before making such a decision we should consider the security flow impact exposing the version string. I think we should **avoid** setting the version via:
- Meta tags
- HTTP Headers
- HTML comments

Better approach for me is showing the framework and the CMS app versions only in the CMS interface as a part of the `footer` or the `Help` page or even a `dedicated page/module` contains all such data.

**Comment by sandio** [comment]
:+1:
