### ISSUE TITLE
Update database dump 

### ISSUE THREAD

**Issue by sandio** [WeAreAthlon/silla.io#48]
Update database dump with a new table 'cache' used by 
Core\Modules\Cache\Adapters\Database to cache key-value pairs in the database.

The dump to be updated is located here:
https://github.com/WeAreAthlon/silla.io/blob/master/vendor/athlon/db/schema.sql

The dump might be appended with:

```
-- Table structure for table `cache`
--

CREATE TABLE IF NOT EXISTS `cache` (
  `cache_key` char(32) NOT NULL,
  `value` text,
  `expire` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by pnikolov** [comment]
I've updated the code for the `cache` table to:

``` SQL
CREATE TABLE IF NOT EXISTS `cache` (
  `cache_key` CHAR(32) NOT NULL,
  `value` TEXT NOT NULL,
  `expire` INT(11) NOT NULL,
  PRIMARY KEY (`cache_key`))
ENGINE = MyISAM;
```
