### ISSUE TITLE
Ability to disable reCAPTCHA when using a development configuration

### ISSUE THREAD

**Issue by sandio** [WeAreAthlon/silla.io#58]
When developing a custom CMS, it is often needed to alter the login action. Then it can be tedious to enter reCAPTCHA on every retry.

**Comment by pnikolov** [comment]
It is acceptable to disable the _reCAPTCHA_ by removing the _reCAPTCHA_ token keys from the `Configuration`? This will avoid adding more configuration variables(_flags to disable, etc_)?
